object Versions {
    const val gradlePlugin = "7.0.1"
    const val kotlin = "1.5.20"
    const val appCompat = "1.4.1"
    const val material = "1.3.0-alpha02"
    const val constraintLayout = "1.1.3"
    const val ktx = "1.7.0"
    const val lottie = "5.0.3"
    const val koin_version = "3.2.0-beta-1"
    const val gson = "2.8.5"
    const val google_service = "4.3.10"
    const val firebase = "30.1.0"
    const val camerax_version = "1.2.0-alpha02"
    const val mlKit_version = "16.1.3"
}